### ISSUE TITLE
Create a Tracker Metrics Dashbaord with Prometheus and Grafana

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-demo#20]
Depends on: https://github.com/torrust/torrust-tracker/issues/1126

Add Prometheus and Grafana containers to the docker-compose configuration.

One example panel with the number of torrents:

![image](https://github.com/user-attachments/assets/f2c7f0f3-1cb8-41c7-8a09-a88f485743d2)

### Subtasks

- [x] Add tracker endpoint.
- [x] Create docker-compose configuration for Prometheus.
- [x] Create docker-compose configuration for Grafana.
- [x] Setup firewall for droplet to close Prometheus port (9090). Prometheus does not have authentication and you can see the tracker API token in the configuration.
- [x] Update docker-compose configuration on the demo server (`/home/torrust/github/torrust/torrust-demo`). 
- [x] Create the dashboard with the panels.
- [x] Setup Grafana with HTTPS (Nginx proxy).

**Comment by josecelano** [comment]
I have set up a basic dashboard:

http://grafana.torrust-demo.com:3100/

![image](https://github.com/user-attachments/assets/f3cf5bd0-629f-4339-948b-5ffaa60458eb)

**Comment by josecelano** [comment]
I've enabled https: https://grafana.torrust-demo.com/

Log into the certbot container:

```
docker compose run --entrypoint /bin/sh certbot
```

Generate staging certificate:

```
/opt/certbot # certbot certonly --webroot --webroot-path=/var/www/html --email my-email@example.com --agree-tos --no-eff-email --staging -d grafana.torrust-de
mo.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for grafana.torrust-demo.com

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/grafana.torrust-demo.com/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/grafana.torrust-demo.com/privkey.pem
This certificate expires on 2025-03-13.
These files will be updated when the certificate renews.

NEXT STEPS:
- The certificate will need to be renewed before it expires. Certbot can automatically renew the certificate in the background, but you may need to take steps to enable that functionality. See https://certbot.org/renewal-setup for instructions.
```

Generate production certificate:

```
 /opt/certbot # certbot certonly --webroot --webroot-path=/var/www/html --email my-email@example.com --agree-tos --no-eff-email --force-renewal -d grafana.torr
ust-demo.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Renewing an existing certificate for grafana.torrust-demo.com

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/grafana.torrust-demo.com/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/grafana.torrust-demo.com/privkey.pem
This certificate expires on 2025-03-13.
These files will be updated when the certificate renews.

NEXT STEPS:
- The certificate will need to be renewed before it expires. Certbot can automatically renew the certificate in the background, but you may need to take steps to enable that functionality. See https://certbot.org/renewal-setup for instructions.
```

**Comment by josecelano** [comment]
[The initial Nginx configuration for Grafana was wrong](https://github.com/torrust/torrust-demo/issues/24). [I've fixed it](https://github.com/torrust/torrust-demo/issues/24).
